M48
; DRILL file {KiCad 7.0.8-7.0.8~ubuntu22.04.1} date Thu 05 Oct 2023 10:55:19 AM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-05T10:55:19-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-7.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.2559
%
G90
G05
T1
X4.77Y-2.01
X4.77Y-4.8946
X5.964Y-2.01
X5.964Y-4.8946
T0
M30
