M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date Tue 30 Jan 2024 10:17:08 AM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-30T10:17:08-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.2559
%
G90
G05
T1
X4.77Y-2.01
X4.77Y-4.8946
X5.964Y-2.01
X5.964Y-4.8946
M30
