M48
; DRILL file {KiCad 7.0.8-7.0.8~ubuntu22.04.1} date Thu 05 Oct 2023 10:53:55 AM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-05T10:53:55-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-7.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0827
%
G90
G05
T1
X7.3415Y-3.9331
X7.3415Y-4.1063
T2
X4.2323Y-3.563
X7.3425Y-3.563
T0
M30
