M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date Thu 22 Feb 2024 09:29:01 AM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-22T09:29:01-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0827
%
G90
G05
T1
X7.3415Y-3.9331
X7.3415Y-4.1063
T2
X4.2323Y-3.563
X7.3425Y-3.563
M30
